Vmc\PatientBundle\Entity\Patient:
 type: entity
 table: patient
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  no_rm:
   type: string
   length: 10
   unique: true
  name:
   type: string
  alamat:
   type: string
  phone:
   type: string
   length: 20
  gender:
   type: string
  birth_date:
   type: date
  addtional_info:
   type: text
  is_delete:
   type: boolean
  is_diabet:
   type: boolean
  diabet_info:
   type: text
  is_blood_issue:
   type: boolean
  blood_issue_info:
   type: text
  is_hiv:
   type: boolean
  hiv_info:
   type: text
  is_hipertensi:
   type: boolean
  hipertensi_info:
   type: text
  is_alergy:
   type: boolean
  alergy_info:
   type: text
  is_others:
   type: boolean
  others_info:
   type: text
